# **************************************************************************
# *
# * Authors: Alberto Garcia Mena   (alberto.garcia@cnb.csic.es)
# *
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

"""
This protocol connect with smartscope in streaming. Recives all information
from the API, collect it in Scipion objects and will be able to communicate
to Smartscope to take decission about the acquisition
"""
from pyworkflow.utils import Message
from pyworkflow import BETA, UPDATED, NEW, PROD
from pwem.protocols.protocol_import.base import ProtImport
from pyworkflow.protocol import ProtStreamingBase, getUpdatedProtocol
from pwem.protocols import EMProtocol

from smartscope import Plugin
from pyworkflow.protocol import params, StringParam
from pwem.objects import SetOfMicrographs, Micrograph
from ..objects.dataCollection import *
from . import smartscopeConnection
from collections import defaultdict

#external imports

class smartscopeSimulator(EMProtocol):
    """
    This protocol will simulate a streaming acquisition with Smartscope. It simulate the set of intensity range calculated by the Feedback micrograph protocol
    The protocol takes the first set of micrographs, the intensityRange calculated for the Feedback Micrograph prptocol and a nes set of micrograph.
    The protocol returns a set of micrographs with the first set unaltered and the second crop by the intensity range criteria.
    """
    """
        Smartscope Simulator (smartscopeSimulator) — User Manual

        Overview

        The Smartscope Simulator protocol reproduces a streaming cryo-EM
        acquisition workflow using Smartscope-related metadata and intensity
        filtering criteria generated by the Feedback Micrograph protocol.
        Its purpose is to simulate how micrographs would be selected during
        automated acquisition based on hole intensity measurements.

        Inputs and Workflow

        The protocol requires a Smartscope connection protocol, a first set
        of filtered micrographs, a second set of non-filtered micrographs,
        and an intensity range previously calculated during feedback analysis.
        During execution, the protocol retrieves movie and hole information
        from the Smartscope session and associates each micrograph with its
        corresponding hole intensity value.

        Intensity-Based Filtering

        The protocol evaluates the intensity associated with each hole and
        compares it against the provided intensity range. Micrographs whose
        hole intensity falls inside the accepted interval are selected and
        added to the output set together with their associated movies.

        The first set of already filtered micrographs is preserved without
        modification, while the second set is filtered dynamically according
        to the intensity criteria. This simulates the behavior of automated
        Smartscope feedback selection during streaming acquisition workflows.

        Outputs and Purpose

        The protocol generates a final set of filtered micrographs together
        with the associated movie set. These outputs reproduce the expected
        acquisition behavior after applying intensity-based selection rules.

        Final Perspective

        Rather than performing image processing directly, this protocol acts
        as a simulation framework for Smartscope feedback workflows. It is
        mainly intended for testing, validation, and development of automated
        cryo-EM acquisition strategies based on micrograph intensity analysis.
        """
    _label = 'Simulator'
    _devStatus = BETA
    _possibleOutputs = {"outputMicrographs" : SetOfMicrographs}


    def __init__(self, **args):
        EMProtocol.__init__(self, **args)

    def _defineParams(self, form):
        """ Define the input parameters that will be used.
        Params:
            form: this is the form to be populated with sections and params.
        """
        # You need a params to belong to a section:
        form.addSection(label=Message.LABEL_INPUT)
        form.addParam('inputProtocol', params.PointerParam,
                      pointerClass='EMProtocol', label="Input Smartscope connection protocols", important=True,
                      help="Smartscope connection protocol")
        form.addParam('micsFiltered', params.PointerParam,
                      pointerClass='SetOfMicrographs', label="Set of micrographs filtered", important=True,
                      help="First set of micrographs with the IntensityRange calculated by Feedback micrograph protocol")
        form.addParam('micsNoFiltered', params.PointerParam, pointerClass='SetOfMicrographs',
                      important=True, allowsNull=False,
                      label='Second set of  micrographs',
                      help='Second set of micrographs.')
        form.addParam('intensityRange', params.StringParam, important=True, allowsPointers=True,
                      label="Intensity Range", pointerClass= StringParam,
                      help='Intensity Range calculated by Feedback Micrograph protocol with the first set of micrographs')

    def _initialize(self):
        # DEBUGALBERTO START
        import os
        fname = "/home/agarcia/Documents/attachActionDebug.txt"
        if os.path.exists(fname):
            os.remove(fname)
        fjj = open(fname, "a+")
        fjj.write('ALBERTO--------->onDebugMode PID {}'.format(os.getpid()))
        fjj.close()
        print('ALBERTO--------->onDebugMode PID {}'.format(os.getpid()))
        import time
        time.sleep(10)
        # DEBUGALBERTO END
        self.dictHoles = {}
        self.dictMovies = {}
        self.setOfMicsNoFiltered = self.micsNoFiltered.get()
        self.setOfMicsFiltered = self.micsFiltered.get()
        self.smartscopeConnectionProtocol = self.getInputProtocol()
        updatedProt = getUpdatedProtocol(self.smartscopeConnectionProtocol)
        if hasattr(updatedProt, 'MoviesSS'):
            self.movies = updatedProt.MoviesSS
        if hasattr(updatedProt, 'Holes'):
            self.holes = updatedProt.Holes
        self.intensityRangeList = [float(x.strip()) for x in self.intensityRange.get().split('-')]

    def getInputProtocol(self):
        prot = self.inputProtocol.get()
        prot.setProject(self.getProject())
        if isinstance(prot, smartscopeConnection):
            return prot
        else:
            return False

    def _insertAllSteps(self):
        self._insertFunctionStep(self._initialize, needsGPU=False)
        self._insertFunctionStep(self.filterMicByIntensity, needsGPU=False)
        self._insertFunctionStep(self.createOutput, needsGPU=False)

    def filterMicByIntensity(self):
        self.info('\n-Filtering micrographs by intensity hole ...')

        for hole in self.holes:
            self.dictHoles[hole.getHoleId()] =  hole.getSelectorValue()

        for m in self.movies:
            self.dictMovies[m.getMicName()] = m.clone()

        self.micsInsideRange = SetOfMicrographs.create(self._getPath())
        self.moviesInsideRange = SetOfMovies.create(self._getPath())

        self.micsInsideRange.copyInfo(self.setOfMicsNoFiltered)
        for mic in self.setOfMicsNoFiltered.iterItems(iterate=False):
            holeId = self.dictMovies[mic.getMicName()].getHoleId()
            intensityHole = self.dictHoles[holeId]
            if min(self.intensityRangeList) <= intensityHole <= max(self.intensityRangeList):
                mic2Add =mic.clone()
                self.micsInsideRange.append(mic2Add)
                self.moviesInsideRange.append(self.dictMovies[mic.getMicName()])

        for mic in self.setOfMicsFiltered.iterItems(iterate=False):
            mic2Add = mic.clone()
            self.micsInsideRange.append(mic2Add)
            self.moviesInsideRange.append(self.dictMovies[mic.getMicName()])

        self.micsInsideRange.write()
        self.moviesInsideRange.write()

    def createOutput(self):
        self.info('\n-Generating outputs ...')
        self.outputsToDefine = {"outputMicrographs" : self.micsInsideRange, "outputMovies" : self.moviesInsideRange}
        self._defineOutputs(** self.outputsToDefine)


